-- Generated by http://typexpert.net online CSV to SQL converter

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('GEOG1131','HUMAN GEOGRAPHY 1: POPULATION, MIGRATION & HUMAN SETTLEMENT','1','','1','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('GEOG1132','HUMAN GEOGRAPHY 2: WORLD ECONOMY, AGRICULTURE & FOOD','1','','1','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('GEOG1231','EARTH ENVIRONMENT 1: GEOMORPHOLOGY & SOILS','1','','2','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('GEOG1232','EARTH ENVIRONMENT 2: CLIMATE & THE BIOSPHERE','1','','2','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('GEOG2131','URBAN GEOGRAPHICS','2','','1','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('GEOG2132','GEOGRAPHIES OF DEVELOPMENT','2','','2','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('GEOG2231','EARTH SURFACE PROCESSES','2','','1','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('GEOG2232','ENVIRONMENTAL CHANGE','2','','2','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('GEOG2331','RESEARCH METHODS IN GEOGRAPHY','2','','2','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('GGEO2233','WATER RESOURCES','2','','1','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('GGEO2332','INTRODUCTION TO GEOGRAPHICAL INFORMATION SYSTEMS','2','','2','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('GEOG3331','GEOGRAPHY OF THE CARIBBEAN ','3','','1','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('GEOG3430','GEOGRAPHY RESEARCH PROJECT','3','','','6');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('GEOG3131','TROPICAL AGRICULTURAL & DEVELOPMENT','3','','1','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('GEOG3132','TROPICAL PLANNING & DEVELOPMENT','3','','2','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('GEOG3333','URBAN AND REGIONAL PLANNING','3','','2','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('GEOG3334','TROPICAL LAND MANAGEMENT','3','','1','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('PHYS0411','INTRODUCTION TO MECHANICS','0','','1','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('PHYS0412','INTRODUCTION TO OSCILLATIONS AND HEAT','0','','1','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('PHYS0421','INTRODUCTION TO ELECTRICITY AND MAGNETISM ','0','','2','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('PHYS1411','MECHANICS','1','','1','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('PHYS1412','WAVES, OPTICS AND THERMODYNAMICS','1','','1','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('PHYS1421','ELECTRICITY AND MAGNETISM','1','','2','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('PHYS1422','MODERN PHYSICS','1','','2','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('ELET1400','INTRODUCTION TO ELECTRONICS','1','','2','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('ELET1405','PRACTICES IN BASIC ELECTRONICS','1','','2','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('PHYS2200','PRACTICES IN MEDICAL PHYSICS I','2','','2','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('PHYS2296','PHYSICS OF THE HUMAN BODY ','2','','1','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('PHYS2300','GENERAL PHYSICS LAB I ','2','','1','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('PHYS2351','QUANTUM MECHANICS & NUCLEAR PHYSICS ','2','','1','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('PHYS2386','ELECTROMAGNETISM AND OPTICS ','2','','1','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('PHYS2396','COMPUTER APPLICATION IN PHYSICS ','2','','1','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('PHYS2500','MATERIALS SCIENCE LABORATORY I ','2','','2','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('PHYS2561','FUNDAMENTALS OF MATERIAL SCIENCE ','2','','2','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('PHYS2600','FLUID DYNAMICS & ENVIRONMENTAL PHYSICS LABORATORY ','2','','2','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('PHYS2671','FLUID DYNAMICS ','2','','2','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('ELET2405','PRACTICES IN ELECTRONICS ','2','','1','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('ELET2410','ANALYSIS AND DESIGN OF ANALOG CIRCUITS','2','','2','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('ELET2415','PRACTICES IN ELECTRONICS DESIGN II','2','','2','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('ELET2420','INTRODUCTION TO SEMICONDUCTOR DEVICES','2','','2','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('ELET2430','DIGITAL CIRCUITS AND MICROPROCESS','2','','1','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('ELET2450','EMBEDDED SYSTEMS','2','','2','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('ELET2460','SIGNALS AND SYSTEMS','2','','1','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('ELET2470','ELECTRIC CIRCUIT ANALYSIS','2','','1','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('ELET2480','MODERN COMMUNICATIONS SYSTEM ','2','','2','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('PHYS3300','ADVANCED PRACTICES IN MEDICAL PHYSICS ','3','','1','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('PHYS3341','BIOMEDICAL OPTICS AND BIOMECHANICS ','3','','1','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('PHYS3386','ELECTROMAGNETISM','3','','2','4');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('PHYS3396','ASTRONOMY & COSMOLOGY ','3','','2','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('PHYS3389','MEDICAL RADIATION PHYSICS AND IMAGING','3','','2','4');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('PHYS3399','RESEARCH PROJECT (NON ELETRONICS) ','3','','1','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('PHYS3500','ADVANCED MATERIALS SCIENCE LABORATORY','3','','1','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('PHYS3561','THE PHYSICS OF CRYSTALLINE METHODS','3','','2','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('PHYS3562','THE PHYSICS OF NON-CRYSTALLINE AND AMORPHOUS MATERIALS','3','','2','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('PHYS3565','THERMODYNAMICS AND KINETICS OF MATERIALS','3','','2','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('PHYS3661','PHYSICS OF ATMOSPHERE AND CLIMATE ','3','','2','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('PHYS3671','SOLAR POWER','3','','1','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('PHYS3681','WIND AND HYDRO POWER','3','','1','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('ELET3405','PRACTICAL ANALYSIS OF ADVANCED ELECTRONIC CIRCUITS AND SYSTEMS','3','','1','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('ELET3430','INSTRUMENTATION AND MEASUREMENTS','3','','1','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('ELET3450','SATELLITE COMMUNICATION & GLOBAL NAVIGATION SYSTEMS','3','','2','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('ELET3460','DIGITAL SIGNAL AND IMAGE PROCESSING','3','','2','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('ELET3470','WAVE TRANSMISSION AND FIBER OPTICS','3','','1','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('ELET3480','WIRELESS COMMUNICATION SYSTEMS','3','','1','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('ELET3440','INTODUCTION TO ROBOTICS','3','','2','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('ELET3490','ELECTRONICS PROJECT','3','','2','4');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('ELET3600','ENERGY SYSTEMS LABORATORY','3','','1','3');

INSERT INTO  (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('ELET3611','INTEGRATING ALTERNATIVE ENERGY','3','','2','3');

