-- Generated by http://typexpert.net online CSV to SQL converter

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP1126','INTRODUCTION TO COMPUTING I','1','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP1127','INTRODUCTION TO COMPUTING II','1','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP1161','OBJECT-OREIENTED PROGRAMMING','1','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP1210','MATHEMATICS FOR COMPUTING','1','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP1220','COMPUTING AND SOCIETY','1','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP2010','PROBABLITY AND STATISTICS','2','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP2120','DIGITAL LOGIC DESIGN','2','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP2130','SYSTEMS PROGRAMMING','2','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP2140','SOFTWARE ENGINEERING','2','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP2170','OBJECT TECHNOLOGY','2','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP2190','NET-CENTRIC COMPUTING','2','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP2201','DISCRETE MATHEMATICS FOR COMPUTER SCIENCE','2','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP2211','ANALYSIS OF ALGORITHMS','2','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP2340','COMPUTER SYSTEMS ORGANIZATION','2','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('INFO2100','MATHEMATICS AND STATISTICS FOR IT','2','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('INFO2110','DATA STRUCTURES FOR IT','2','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('INFO2180','DYNAMIC WEB DEVELOPMENT I','2','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP3101','OPERATING SYSTEMS','3','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP3161','DATABASE MANAGEMENT SYSTEMS','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP3191','PRINCIPLES OF COMPUTER NETWORKING','3','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP3192','IMPLEMENTATION OF COMPUTER NETWORKS','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP3220','PRINCIPLES OF ARTIFICIAL INTELLIGENCE','3','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP3270','USER INTERFACE DESIGN','3','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP3652','LANGUAGE PROCESSORS','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP3702','THEORY OF COMPUTATION','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP3801','REAL-TIME EMBEDDED SYSTEMS','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP3901','CAPSTONE PROJECT','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP3911','INTERNSHIP IN COMPUTING I','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP3912','INTERNSHIP IN COMPUTING II','3','','2','6');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('INFO3105','COMPUTER SYSTEMS ADMINISTRATION','3','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('INFO3110','INFORMATION SYSTEMS','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('INFO3155','INFORMATION ASSURANCE AND SECURITY','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('INFO3170','USER INTERFACE DESIGN FOR IT','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('INFO3180','DYNAMIC WEB DEVELOPMENT II','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('INFO3435','ECOMMERCE','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('SWEN3130','SOFTWARE PROJECT MANAGEMENT','3','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('SWEN3145','SOFTWARE MODELING','3','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('SWEN3165','SOFTWARE TESTING','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('SWEN3185','FORMAL METHODS AND SOFTWARE REALIABLITY','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('SWEN3920','CAPSTONE PROJECT (SOFTWARE ENGINEERING)','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH1141','INTRODUCTORY LINEAR ALGEBRA AND ANALYTIC GEOMETRY','1','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH1142','CALCULUS I','1','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH1151','CALCULUS II','1','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH1152','INTRODUCTION TO FORMAL MATHEMATICS','1','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH1180','ENGINEERING MATHEMATICS I','1','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH1185','CALCULUS FOR SCIENTIST AND ENGINEERS','1','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('STAT1001','STATISTICS FOR THE SCIENTISTS','1','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH2401','ELEMENTS OF MATHEMATICAL ANALYSIS','2','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH2230','ENGINEERING MATHEMATICS II','2','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH2404','INTRODUCTION TO PROBABLITY THEORY','2','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH2407','STOCHASTIC MODELLING','2','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH2410','A FIRST COUSRE IN LINEAR ALGEEBRA','2','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH2411','INTRODUCTION TO ABSTRACT ALGEBRA','2','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH2420','ORDINARY DIFFERENTIAL EQUATIONS','2','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH2421','FOURIER SERIES AND INTEGRAL TRANSFORMS','2','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH2430','LINEAR OPTIMIZATION','2','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH2431','NON-LINEAR OPTIMIZATION','2','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH2701','ACTURIAL MATHEMATICS I','2','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('STAT2001','INFERENTIAL STATISTICS','2','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('STAT2002','DISCRETE STATISTICS','2','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('STAT2003','LINEAR MODELS','2','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('STAT2004','MULTIVARIATE METHODS','2','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH3400','COMPLEX VARIABLES','3','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH3401','INTRODUCTION TO THE THEORY OF INTEGRATION','3','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH3402','A COURSE ON METRIC SPACES AND TOPOLOGY','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH3403','SOME TOPICS IN FUNCTIONAL ANALYSIS','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH3404','INTRODUCTION TO DIFFERENTIAL GEOMETRY WITH COMPUTER SOFTWARE','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH3405','NUMBER THEORY','3','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH3411','ADVANCED ABSTRACT ALGEBRA','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH3412','ADVANCED LINEAR ALGEBRA','3','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH3414','SELECTED TOPICS IN OPERATIONS RESEARCH','3','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH3421','PARTIAL DIFFERENTIAL EQUATIONS','3','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH3422','MATHEMATICAL MODELLING','3','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH3423','RESEARCH PROJECT IN MATHEMATICS','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH3424','NUMERICAL METHODS','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH3425','TECHNIQUES FOR SOLVING ADVANCED MATHEMATICS PROBLEMS','3','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH3801','FINANCIAL MATHEMATICS II','3','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH3802','EVALUATION ACTURIAL MODELS','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH3803','MODELS FOR FINANCIAL ECONOMICS','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH3804','ACTURIAL MATHEMATICS II','3','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH3805','MATHEMATICS OF PENSION FUNDS','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH3806','TOPICS IN GENERAL INSURANCE','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('STAT3001','REGRESSION ANALYSIS','3','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('STAT3002','TIME SERIES','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('STAT3003','DESIGN & ANALYSIS OF EXPERIMENTS','3','','2','3');

