
DROP DATABASE IF EXISTS capstone;
CREATE DATABASE capstone;
USE capstone;

CREATE TABLE studentpersonal 
(	
	stid int,
	fname varchar(25),
	lname varchar(25),
	password varchar(25),
	email varchar(50),

	primary key (stid)

);

create table student
	(
		stid int,
		major1 varchar(25),
		major2 varchar(25),
		minor1 varchar(25),
		minor2 varchar(25),
		level int,
		status varchar(10),
		primary key (stid),
		FOREIGN KEY (stid) REFERENCES studentpersonal(stid)
	);

create table courses
	(
		c_code varchar (25),
		c_name varchar (50),
		c_level int,
		c_descrip varchar(500),
		semester int,
		creditnum int,


		primary key (c_code)

	);

create table prereq
(
	id int not null AUTO_INCREMENT,
	c_code varchar(8),
	prereq_code varchar(8),
	primary key (id),
	FOREIGN KEY (c_code) REFERENCES courses(c_code),
	FOREIGN KEY (prereq_code) REFERENCES courses(c_code)

);


create table degrees	/*Need to find a away to account for majors and minors */
	(
		id int auto_increment NOT NULL,
		name varchar(50),
		department varchar(50),
		type varchar(50),

		primary key (id)

	);

	create table requirements
		(
			id int not null AUTO_INCREMENT,
			degree_name varchar(50),
			core_course varchar(25),
			primary key (id),
			FOREIGN KEY (core_course) REFERENCES courses(c_code)
			/*FOREIGN KEY (name) REFERENCES courses(c_code)*/
		);



create table lecturer
	(
		lec_id int,
		lec_name varchar(50),
		lec_code varchar(8),

		primary key (lec_id),
		FOREIGN KEY (lec_code) REFERENCES courses(c_code)

	);


create table cxc
	(
		id int not null AUTO_INCREMENT,
		cxc_name varchar(50),
		type varchar(25),
		primary key(id)
	);



-- ---------------------------------------------POPULATION-------------------------------------------------------------------------------------------------
-- Generated by http://typexpert.net online CSV to SQL converter

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP1126','INTRODUCTION TO COMPUTING I','1','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP1127','INTRODUCTION TO COMPUTING II','1','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP1161','OBJECT-OREIENTED PROGRAMMING','1','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP1210','MATHEMATICS FOR COMPUTING','1','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP1220','COMPUTING AND SOCIETY','1','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP2010','PROBABLITY AND STATISTICS','2','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP2120','DIGITAL LOGIC DESIGN','2','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP2130','SYSTEMS PROGRAMMING','2','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP2140','SOFTWARE ENGINEERING','2','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP2170','OBJECT TECHNOLOGY','2','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP2190','NET-CENTRIC COMPUTING','2','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP2201','DISCRETE MATHEMATICS FOR COMPUTER SCIENCE','2','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP2211','ANALYSIS OF ALGORITHMS','2','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP2340','COMPUTER SYSTEMS ORGANIZATION','2','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('INFO2100','MATHEMATICS AND STATISTICS FOR IT','2','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('INFO2110','DATA STRUCTURES FOR IT','2','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('INFO2180','DYNAMIC WEB DEVELOPMENT I','2','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP3101','OPERATING SYSTEMS','3','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP3161','DATABASE MANAGEMENT SYSTEMS','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP3191','PRINCIPLES OF COMPUTER NETWORKING','3','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP3192','IMPLEMENTATION OF COMPUTER NETWORKS','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP3220','PRINCIPLES OF ARTIFICIAL INTELLIGENCE','3','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP3270','USER INTERFACE DESIGN','3','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP3652','LANGUAGE PROCESSORS','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP3702','THEORY OF COMPUTATION','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP3801','REAL-TIME EMBEDDED SYSTEMS','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP3901','CAPSTONE PROJECT','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP3911','INTERNSHIP IN COMPUTING I','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('COMP3912','INTERNSHIP IN COMPUTING II','3','','2','6');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('INFO3105','COMPUTER SYSTEMS ADMINISTRATION','3','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('INFO3110','INFORMATION SYSTEMS','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('INFO3155','INFORMATION ASSURANCE AND SECURITY','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('INFO3170','USER INTERFACE DESIGN FOR IT','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('INFO3180','DYNAMIC WEB DEVELOPMENT II','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('INFO3435','ECOMMERCE','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('SWEN3130','SOFTWARE PROJECT MANAGEMENT','3','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('SWEN3145','SOFTWARE MODELING','3','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('SWEN3165','SOFTWARE TESTING','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('SWEN3185','FORMAL METHODS AND SOFTWARE REALIABLITY','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('SWEN3920','CAPSTONE PROJECT (SOFTWARE ENGINEERING)','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH1141','INTRODUCTORY LINEAR ALGEBRA AND ANALYTIC GEOMETRY','1','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH1142','CALCULUS I','1','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH1151','CALCULUS II','1','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH1152','INTRODUCTION TO FORMAL MATHEMATICS','1','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH1180','ENGINEERING MATHEMATICS I','1','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH1185','CALCULUS FOR SCIENTIST AND ENGINEERS','1','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('STAT1001','STATISTICS FOR THE SCIENTISTS','1','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH2401','ELEMENTS OF MATHEMATICAL ANALYSIS','2','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH2230','ENGINEERING MATHEMATICS II','2','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH2404','INTRODUCTION TO PROBABLITY THEORY','2','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH2407','STOCHASTIC MODELLING','2','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH2410','A FIRST COUSRE IN LINEAR ALGEEBRA','2','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH2411','INTRODUCTION TO ABSTRACT ALGEBRA','2','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH2420','ORDINARY DIFFERENTIAL EQUATIONS','2','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH2421','FOURIER SERIES AND INTEGRAL TRANSFORMS','2','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH2430','LINEAR OPTIMIZATION','2','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH2431','NON-LINEAR OPTIMIZATION','2','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH2701','ACTURIAL MATHEMATICS I','2','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('STAT2001','INFERENTIAL STATISTICS','2','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('STAT2002','DISCRETE STATISTICS','2','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('STAT2003','LINEAR MODELS','2','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('STAT2004','MULTIVARIATE METHODS','2','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH3400','COMPLEX VARIABLES','3','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH3401','INTRODUCTION TO THE THEORY OF INTEGRATION','3','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH3402','A COURSE ON METRIC SPACES AND TOPOLOGY','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH3403','SOME TOPICS IN FUNCTIONAL ANALYSIS','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH3404','INTRODUCTION TO DIFFERENTIAL GEOMETRY WITH COMPUTER SOFTWARE','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH3405','NUMBER THEORY','3','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH3411','ADVANCED ABSTRACT ALGEBRA','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH3412','ADVANCED LINEAR ALGEBRA','3','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH3414','SELECTED TOPICS IN OPERATIONS RESEARCH','3','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH3421','PARTIAL DIFFERENTIAL EQUATIONS','3','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH3422','MATHEMATICAL MODELLING','3','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH3423','RESEARCH PROJECT IN MATHEMATICS','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH3424','NUMERICAL METHODS','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH3425','TECHNIQUES FOR SOLVING ADVANCED MATHEMATICS PROBLEMS','3','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH3801','FINANCIAL MATHEMATICS II','3','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH3802','EVALUATION ACTURIAL MODELS','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH3803','MODELS FOR FINANCIAL ECONOMICS','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH3804','ACTURIAL MATHEMATICS II','3','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH3805','MATHEMATICS OF PENSION FUNDS','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('MATH3806','TOPICS IN GENERAL INSURANCE','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('STAT3001','REGRESSION ANALYSIS','3','','1','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('STAT3002','TIME SERIES','3','','2','3');

INSERT INTO courses (`c_code`,`c_name`,`c_level`,`c_descrip`,`semester`,`creditnum`) VALUES ('STAT3003','DESIGN & ANALYSIS OF EXPERIMENTS','3','','2','3');


INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('1','BIOCHEMISTRY','MEDICAL SCIENCES','MAJOR');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('2','BIOTECHNOLOGY','MEDICAL SCIENCES','MAJOR');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('3','MICROBIOLOGY','MEDICAL SCIENCES','MAJOR');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('4','MOLECULAR BIOLOGY','MEDICAL SCIENCES','MAJOR');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('5','APPLIED CHEMISTRY','CHEMISTRY','MAJOR');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('6','GENERAL CHEMISTRY','CHEMISTRY','MAJOR');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('7','ENVIRONMENTAL CHEMISTRY','CHEMISTRY','MAJOR');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('8','FOOD CHEMISTRY','CHEMISTRY','MAJOR');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('9','ENVIRONMENTAL CHEMISTRY','CHEMISTRY','MINOR');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('10','FOOD CHEMISTRY','CHEMISTRY','MINOR');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('11','FOOD PROCESSING','CHEMISTRY','MINOR');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('12','GENERAL CHEMISTRY','CHEMISTRY','MINOR');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('13','INDUSTRIAL CHEMISTRY','CHEMISTRY','MINOR');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('14','COMPUTER SCIENCE','COMPUTING','MAJOR');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('15','SOFTWARE ENGINEERING','COMPUTING','MAJOR');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('16','COMPUTER STUDIES','COMPUTING','SPECIAL');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('17','COMPUTER SYSTEMS ENGINEERING','COMPUTING','SPECIAL');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('18','INFORMATION TECHNOLOGY','COMPUTING','SPECIAL');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('19','GEOGRAPHY','GEOGRAPHY AND GEOLOGY','MAJOR');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('20','GEOLOGY','GEOGRAPHY AND GEOLOGY','MAJOR');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('21','GEOGRAPHY','GEOGRAPHY AND GEOLOGY','MINOR');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('22','GEOLOGY','GEOGRAPHY AND GEOLOGY','MINOR');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('23','ELECTRONICS','PHYSICS','MAJOR');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('24','ENERGY AND ENVIRONMENTAL PHYSICS','PHYSICS','MAJOR');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('25','GENERAL PHYSICS','PHYSICS','MAJOR');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('26','MATERIALS SCIENCE','PHYSICS','MAJOR');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('27','MEDICAL PHYSICS','PHYSICS','MAJOR');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('28','ELECTRONICS','PHYSICS','MINOR');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('29','ENERGY AND ENVIRONMENTAL PHYSICS','PHYSICS','MINOR');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('30','GENERAL PHYSICS','PHYSICS','MINOR');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('31','MATERIALS SCIENCE','PHYSICS','MINOR');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('32','MEDICAL PHYSICS','PHYSICS','MINOR');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('33','PHYSICS WITH EDUCATION','PHYSICS','SPECIAL');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('34','MATHEMATICS','MATHEMATICS','MAJOR');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('35','MATHEMATICS AND MODELLING PROCESSES(DOUBLE)','MATHEMATICS','MAJOR');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('36','MATHEMATICS','MATHEMATICS','MINOR');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('37','ACTUARIAL SCIENCE','MATHEMATICS','SPECIAL');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('38','MATHEMATICS WITH EDUCATION','MATHEMATICS','SPECIAL');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('39','ANIMAL BIOLOGY','LIFE SCIENCES','MAJOR');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('40','PLANT BIOLOGY','LIFE SCIENCES','MAJOR');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('41','HORTICULTURE','LIFE SCIENCES','MAJOR');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('42','MARINE BIOLOGY','LIFE SCIENCES','MAJOR');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('43','TERRESTRIAL AND FRESHWATER ECOLOGY','LIFE SCIENCES','MAJOR');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('44','ANIMAL BIOLOGY','LIFE SCIENCES','MINOR');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('45','PLANT BIOLOGY','LIFE SCIENCES','MINOR');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('46','COASTAL ECOSYSTEMS','LIFE SCIENCES','MINOR');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('47','TERRESTRIAL AND FRESHWATER ECOLOGY','LIFE SCIENCES','MINOR');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('48','BIOLOGY WITH EDUCATION','LIFE SCIENCES','SPECIAL');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('49','ENVIRONMENTAL BIOLOGY','LIFE SCIENCES','SPECIAL');

INSERT INTO degrees (`id`,`name`,`department`,`type`) VALUES ('50','EXPERIMENTAL BIOLOGY','LIFE SCIENCES','SPECIAL');


INSERT INTO studentpersonal (`stid`,`fname`,`lname`,`password`,`email`) VALUES ('620000001','John','Doe','password','johndoe@gmail.com');

INSERT INTO studentpersonal (`stid`,`fname`,`lname`,`password`,`email`) VALUES ('420000002','Jane','Doe','password','janedoe@gmail.com');

INSERT INTO studentpersonal (`stid`,`fname`,`lname`,`password`,`email`) VALUES ('520000003','SammyÊ','Joe','password','sammyjoe@gmail.com');


